### ISSUE TITLE
tsum_TOST vs TOSTone

### ISSUE THREAD

**Issue by NikdAK** [cran/TOSTER#1]
I am currently using TOSTone and wanted to switch to tsum_TOST due to the message "Note: this function is defunct. Please use tsum_TOST instead". 

Anyways, I noticed that I can not reproduce my results using tsum_TOST, the results are different. Any idea what might be wrong? 

[TOST_values.txt](https://github.com/cran/TOSTER/files/9478769/TOST_values.txt)

```
values <- read.csv("TOST_values.txt", header = F)$V1

TOSTone(m=mean(values),sd=sd(values),n=length(values),mu=0.742,low_eqbound_d=-3, high_eqbound_d=3, alpha=0.05, plot = F)

tsum_TOST(m1=mean(values),sd1=sd(values),n1=length(values),mu=0.742,low_eqbound=-3, high_eqbound=3, alpha=0.05, eqbound_type="SMD")
```

Also I tried to switch to raw instead of SMD, but this results in everything being significant all the time.

```
lowEQ <- mean(values) - sd(values)*3
highEQ <- mean(values) + sd(values)*3
tsum_TOST(m1=mean(values),sd1=sd(values),n1=length(values),mu=0.742,low_eqbound=lowEQ, high_eqbound=highEQ, alpha=0.05)
```

Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
